[build]
<<<<<<< Updated upstream
  publish = "dist/anglify"
=======
  publish = "dist/"
>>>>>>> Stashed changes
  command = "npm run build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
